export type CastDetail = {
  rankID: string;
  rank: string;
  castId: string;
  castName: string;
  castImage: string;
  castImageSquare?: string;
  profileImages: string[];
  age: number;
  tall: number;
  bust: number;
  cup: string;
  west: number;
  hip: number;
  castUrl: string;
  shopId: string;
  shopName: string;
  realTimeStatus: number;
  realTimeDetail: string;
  realTimeComment: string;
  startTime: string;
  endTime: string;
  scheduleStatus: string;
  gradeId: number;
  type: number[];
  badges?: string[];
};
